import Layout from '@/components/Layout';
import Head from 'next/head';
import Image from 'next/image';
import profilePic from '../../public/images/profile/otra1.png';
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link';
import { LinkArrow } from '@/components/Icons';
import HireMe from '@/components/HireMe';
import TransitionEffect from '@/components/TransitionEffect';

export default function Home() {
  return (
    <>
      <Head>
        <title>Izamul Fikri | Portfolio</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <TransitionEffect />
      <main className=' flex items-center text-dark w-full min-h-screen dark:text-light '>
        <Layout className='pt-0 md:p-16 sm:p-8'>
          <div className='flex items-center justify-between w-full lg:flex-col'>
            <div className='w-3/8 md:w-[85%] image-overlay inset-0 pointer-events-none'>
              <Image
                src={profilePic}
                alt='IzamulFikri-Dev'
                className='w-full h-auto lg:hidden md:inline-block md:w-full'
                priority
                sizes='(max-width: 768px) 80vw,
              (max-width: 1200px) 40vw,
              30vw'
              />
            </div>
            <div className='w-1/2 space-x-2 flex flex-col items-center self-center lg:w-full lg:text-center'>
              <AnimatedText
                text='Hola, aku Izamul Fikri'
                delay={800}
                className='!text-5xl !text-left
              xl:!text-5xl lg:!text-center lg:!text-5xl md:!text-5xl sm:!text-3xl
              '
              />
              <p className='my-4 text-base space-x-2 font-medium md:text-sm sm:text-xs text-justify  whitespace-normal'>
              Selamat datang di portofolio saya! 
              Saya memiliki minat yang besar dalam pengembangan aplikasi mobile, 
              baik menggunakan teknologi native maupun cross-platform seperti Flutter. 
              Selain itu, saya juga mahir dalam pengembangan web menggunakan Laravel dan 
              mengatur REST API menggunakan Flask. Pengalaman saya sebagai network engineer 
              juga memungkinkan saya untuk menyediakan layanan internet yang handal. 
              Mari kita jelajahi beberapa proyek yang telah saya selesaikan.
              </p>
              <div className='flex items-center space-x-4 self-start mt-2 lg:self-center'>
                <Link
                  href='/CV.Volonterio.Gonzalo.pdf'
                  target={'_blank'}
                  aria-label='My Cv'
                  className='flex items-center bg-dark text-light p-2.5 px-6
                rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
                border-2 border-solid border-transparent hover:border-dark
                dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light
                hover:dark:border-light md:p-2 md:px-4 md:text-base
                '
                  download={true}
                >
                  Unduh CV <LinkArrow className={'w-4 ml-2'} />
                </Link>
                <Link
                  href='mailto:fikriizamul@gmail.com'
                  target={'_blank'}
                  aria-label='To talk to me'
                  className='flex items-center bg-dark text-light p-2.5 px-6
                rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
                border-2 border-solid border-transparent hover:border-dark
                dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light
                hover:dark:border-light md:p-2 md:px-4 md:text-base
                '
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>

        <HireMe />
      </main>
    </>
  );
}
